# Billboard hot 100 data exploration and cleaning

In [3]:
import pandas as pd
hot100_chart_df = pd.read_csv("../data/hot-100-current.csv")

Inspect the original Billboard Hot 100 data.

In [4]:
hot100_chart_df.head()

,chart_week,current_week,title,performer,last_week,peak_pos,wks_on_chart
0,2022-01-01,1,All I Want For Christmas Is You,Mariah Carey,1.0,1,50
1,2022-01-01,2,Rockin' Around The Christmas Tree,Brenda Lee,2.0,2,44
2,2022-01-01,3,Jingle Bell Rock,Bobby Helms,4.0,3,41
3,2022-01-01,4,A Holly Jolly Christmas,Burl Ives,5.0,4,25
4,2022-01-01,5,Easy On Me,Adele,3.0,1,11

In [5]:
hot100_chart_df.shape

(354800, 7)

In [6]:
hot100_chart_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 354800 entries, 0 to 354799
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   chart_week    354800 non-null  str
 1   current_week  354800 non-null  int64
 2   title         354800 non-null  str
 3   performer     354800 non-null  str
 4   last_week     322340 non-null  float64
 5   peak_pos      354800 non-null  int64
 6   wks_on_chart  354800 non-null  int64
dtypes: float64(1), int64(3), str(3)
memory usage: 32.8 MB

In [7]:
hot100_chart_df.describe(include="all")

,chart_week,current_week,title,performer,last_week,peak_pos,wks_on_chart
count,354800,354800.000000,354800,354800,322340.000000,354800.000000,354800.00000
unique,3548,NaN,27030,11278,NaN,NaN,NaN
top,2022-01-01,NaN,Stay,Taylor Swift,NaN,NaN,NaN
freq,100,NaN,271,1769,NaN,NaN,NaN
mean,NaN,50.500000,NaN,NaN,46.921518,40.388926,9.45971
std,NaN,28.866034,NaN,NaN,28.321535,29.298040,8.21829
min,NaN,1.000000,NaN,NaN,0.000000,1.000000,1.00000
25%,NaN,26.000000,NaN,NaN,22.000000,13.000000,4.00000
50%,NaN,51.000000,NaN,NaN,46.000000,37.000000,7.00000
75%,NaN,75.000000,NaN,NaN,71.000000,65.000000,13.00000
max,NaN,100.000000,NaN,NaN,100.000000,100.000000,112.00000

Notice: 
* "chart_week" is of str type.

In [8]:
hot100_chart_df["chart_week"] = pd.to_datetime(hot100_chart_df["chart_week"])
hot100_chart_df = hot100_chart_df.sort_values(["chart_week", "current_week"])

In [9]:
hot100_chart_df

,chart_week,current_week,title,performer,last_week,peak_pos,wks_on_chart
24000,1958-08-04,1,Poor Little Fool,Ricky Nelson,NaN,1,1
24001,1958-08-04,2,Patricia,Perez Prado And His Orchestra,NaN,2,1
24002,1958-08-04,3,Splish Splash,Bobby Darin,NaN,3,1
24003,1958-08-04,4,Hard Headed Woman,Elvis Presley With The Jordanaires,NaN,4,1
24004,1958-08-04,5,When,Kalin Twins,NaN,5,1
...,...,...,...,...,...,...,...
23995,2026-08-01,96,In My Room,Julia Wolf,0.0,57,12
23996,2026-08-01,97,Empty Words,Corey Kent,0.0,93,6
23997,2026-08-01,98,No Need For Leavin',Kameron Marlowe,0.0,98,2
23998,2026-08-01,99,Minibar,Gracie Abrams,0.0,99,1
23999,2026-08-01,100,Kingdom Of Fear,Cameron Whitcomb,0.0,94,5

The original table contains Billboard Hot 100 data from 1958-08-04 to 2026-08-01.

Notice:
* "last_week" has NaN and is of float64 type. Meantime it also has 0.

We want to see if there is any difference between 0 and NaN.

In [10]:
hot100_chart_df[hot100_chart_df["last_week"].isna()]

,chart_week,current_week,title,performer,last_week,peak_pos,wks_on_chart
24000,1958-08-04,1,Poor Little Fool,Ricky Nelson,NaN,1,1
24001,1958-08-04,2,Patricia,Perez Prado And His Orchestra,NaN,2,1
24002,1958-08-04,3,Splish Splash,Bobby Darin,NaN,3,1
24003,1958-08-04,4,Hard Headed Woman,Elvis Presley With The Jordanaires,NaN,4,1
24004,1958-08-04,5,When,Kalin Twins,NaN,5,1
...,...,...,...,...,...,...,...
354181,2021-12-25,82,Man In The Mirror,A Boogie Wit da Hoodie,NaN,82,1
354184,2021-12-25,85,To Be Loved By You,Parker McCollum,NaN,85,3
354185,2021-12-25,86,From My Window,Juice WRLD,NaN,86,1
354186,2021-12-25,87,Relocate,Juice WRLD,NaN,87,1
354197,2021-12-25,98,Feel Alone,Juice WRLD,NaN,98,1

In [11]:
hot100_chart_df[hot100_chart_df["last_week"]==0]

,chart_week,current_week,title,performer,last_week,peak_pos,wks_on_chart
13,2022-01-01,14,Broadway Girls,Lil Durk Featuring Morgan Wallen,0.0,14,1
32,2022-01-01,33,Jingle Bells,Frank Sinatra,0.0,33,3
36,2022-01-01,37,Linus & Lucy,Vince Guaraldi Trio,0.0,37,1
39,2022-01-01,40,Please Come Home For Christmas,Eagles,0.0,18,10
40,2022-01-01,41,Santa Claus Is Comin' To Town,Jackson 5,0.0,41,2
...,...,...,...,...,...,...,...
23995,2026-08-01,96,In My Room,Julia Wolf,0.0,57,12
23996,2026-08-01,97,Empty Words,Corey Kent,0.0,93,6
23997,2026-08-01,98,No Need For Leavin',Kameron Marlowe,0.0,98,2
23998,2026-08-01,99,Minibar,Gracie Abrams,0.0,99,1
23999,2026-08-01,100,Kingdom Of Fear,Cameron Whitcomb,0.0,94,5

It turns out that using 0 instead of NaN is just an inconsistency that started in 2022.

In [12]:
hot100_chart_df[(hot100_chart_df["title"] == "Poor Little Fool") & (hot100_chart_df["performer"] == "Ricky Nelson")]

,chart_week,current_week,title,performer,last_week,peak_pos,wks_on_chart
24000,1958-08-04,1,Poor Little Fool,Ricky Nelson,NaN,1,1
24100,1958-08-11,1,Poor Little Fool,Ricky Nelson,1.0,1,2
24203,1958-08-18,4,Poor Little Fool,Ricky Nelson,1.0,1,3
24305,1958-08-25,6,Poor Little Fool,Ricky Nelson,4.0,1,4
24404,1958-09-01,5,Poor Little Fool,Ricky Nelson,6.0,1,5
24505,1958-09-08,6,Poor Little Fool,Ricky Nelson,5.0,1,6
24612,1958-09-15,13,Poor Little Fool,Ricky Nelson,6.0,1,7
24718,1958-09-22,19,Poor Little Fool,Ricky Nelson,13.0,1,8
24835,1958-09-29,36,Poor Little Fool,Ricky Nelson,19.0,1,9
24946,1958-10-06,47,Poor Little Fool,Ricky Nelson,36.0,1,10
25070,1958-10-13,71,Poor Little Fool,Ricky Nelson,47.0,1,11

In [13]:
hot100_chart_df[(hot100_chart_df["title"] == "In My Room") & (hot100_chart_df["performer"] == "Julia Wolf")]

,chart_week,current_week,title,performer,last_week,peak_pos,wks_on_chart
22098,2026-03-21,99,In My Room,Julia Wolf,0.0,99,1
22163,2026-03-28,64,In My Room,Julia Wolf,99.0,64,2
22266,2026-04-04,67,In My Room,Julia Wolf,64.0,64,3
22359,2026-04-11,60,In My Room,Julia Wolf,67.0,60,4
22456,2026-04-18,57,In My Room,Julia Wolf,60.0,57,5
22560,2026-04-25,61,In My Room,Julia Wolf,57.0,57,6
22662,2026-05-02,63,In My Room,Julia Wolf,61.0,57,7
22781,2026-05-09,82,In My Room,Julia Wolf,63.0,57,8
22884,2026-05-16,85,In My Room,Julia Wolf,82.0,57,9
22981,2026-05-23,82,In My Room,Julia Wolf,85.0,57,10
23594,2026-07-04,95,In My Room,Julia Wolf,0.0,57,11
23995,2026-08-01,96,In My Room,Julia Wolf,0.0,57,12

In [14]:
assert (hot100_chart_df["chart_week"] == "2026-06-27").any() # There is data for 2026-06-27 
assert (hot100_chart_df["chart_week"] == "2026-07-25").any() # There is data for 2026-07-25

We have more evidence that both 0 and NaN mean the song was not on chart the last week. So replace all 0 with \<NA\>.

In [15]:
hot100_chart_df["last_week"] = hot100_chart_df["last_week"].replace(0, pd.NA).astype("Int64")

In [16]:
hot100_chart_df

,chart_week,current_week,title,performer,last_week,peak_pos,wks_on_chart
24000,1958-08-04,1,Poor Little Fool,Ricky Nelson,<NA>,1,1
24001,1958-08-04,2,Patricia,Perez Prado And His Orchestra,<NA>,2,1
24002,1958-08-04,3,Splish Splash,Bobby Darin,<NA>,3,1
24003,1958-08-04,4,Hard Headed Woman,Elvis Presley With The Jordanaires,<NA>,4,1
24004,1958-08-04,5,When,Kalin Twins,<NA>,5,1
...,...,...,...,...,...,...,...
23995,2026-08-01,96,In My Room,Julia Wolf,<NA>,57,12
23996,2026-08-01,97,Empty Words,Corey Kent,<NA>,93,6
23997,2026-08-01,98,No Need For Leavin',Kameron Marlowe,<NA>,98,2
23998,2026-08-01,99,Minibar,Gracie Abrams,<NA>,99,1
23999,2026-08-01,100,Kingdom Of Fear,Cameron Whitcomb,<NA>,94,5

In [17]:
hot100_chart_df.to_parquet("../data/hot-100-chart_current.parquet", index=False) #overwrite everytime

---

In [18]:
hot100_song_df = hot100_chart_df.drop(columns=["current_week", "last_week"])
hot100_song_df = hot100_song_df.sort_values(["title", "performer", "chart_week"])
hot100_song_df = hot100_song_df[["title", "performer", "chart_week", "wks_on_chart", "peak_pos"]]

In [19]:
hot100_song_df.head()

            title           performer chart_week  wks_on_chart  peak_pos
188283  "B" Girls  Young And Restless 1990-05-05             1        84
188377  "B" Girls  Young And Restless 1990-05-12             2        78
188467  "B" Girls  Young And Restless 1990-05-19             3        68
188559  "B" Girls  Young And Restless 1990-05-26             4        60
188657  "B" Girls  Young And Restless 1990-06-02             5        58

In [20]:
hot100_song_df.info()

<class 'pandas.DataFrame'>
Index: 354800 entries, 188283 to 26246
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   title         354800 non-null  str
 1   performer     354800 non-null  str
 2   chart_week    354800 non-null  datetime64[us]
 3   wks_on_chart  354800 non-null  int64
 4   peak_pos      354800 non-null  int64
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 26.8 MB

Before we check duplicates, we want to confirm the meaning of "wks_on_chart" and "peak_pos". 

If a song returns to the Billboard Hot 100 after being off the chart for a while,
* Does "wks_on_chart" include its previous weeks on the chart? 
* Does "peak_pos" still have the memory of the past?

The previous experiment on Julia Wolf's "In My Room" seems to confirm that the answer to both questions is yes.

In [21]:
duplicates = hot100_song_df.duplicated(
    subset=["title", "performer", "wks_on_chart"],
    keep=False
)
duplicates.any()

np.True_

In [22]:
hot100_song_df[duplicates]

,title,performer,chart_week,wks_on_chart,peak_pos
44365,Breaking Up Is Hard To Do,Neil Sedaka,1962-06-30,1,66
44425,Breaking Up Is Hard To Do,Neil Sedaka,1962-07-07,2,26
44518,Breaking Up Is Hard To Do,Neil Sedaka,1962-07-14,3,19
44612,Breaking Up Is Hard To Do,Neil Sedaka,1962-07-21,4,13
44707,Breaking Up Is Hard To Do,Neil Sedaka,1962-07-28,5,8
...,...,...,...,...,...
185656,What About Me,Moving Pictures,1989-11-04,13,46
185765,What About Me,Moving Pictures,1989-11-11,14,46
185870,What About Me,Moving Pictures,1989-11-18,15,46
185980,What About Me,Moving Pictures,1989-11-25,16,46
186091,What About Me,Moving Pictures,1989-12-02,17,46

In [23]:
hot100_song_df[(hot100_song_df["title"]=="Breaking Up Is Hard To Do") & (hot100_song_df["performer"]=="Neil Sedaka")]

,title,performer,chart_week,wks_on_chart,peak_pos
44365,Breaking Up Is Hard To Do,Neil Sedaka,1962-06-30,1,66
44425,Breaking Up Is Hard To Do,Neil Sedaka,1962-07-07,2,26
44518,Breaking Up Is Hard To Do,Neil Sedaka,1962-07-14,3,19
44612,Breaking Up Is Hard To Do,Neil Sedaka,1962-07-21,4,13
44707,Breaking Up Is Hard To Do,Neil Sedaka,1962-07-28,5,8
44801,Breaking Up Is Hard To Do,Neil Sedaka,1962-08-04,6,2
44900,Breaking Up Is Hard To Do,Neil Sedaka,1962-08-11,7,1
45000,Breaking Up Is Hard To Do,Neil Sedaka,1962-08-18,8,1
45101,Breaking Up Is Hard To Do,Neil Sedaka,1962-08-25,9,1
45202,Breaking Up Is Hard To Do,Neil Sedaka,1962-09-01,10,1
45305,Breaking Up Is Hard To Do,Neil Sedaka,1962-09-08,11,1
45410,Breaking Up Is Hard To Do,Neil Sedaka,1962-09-15,12,1
45533,Breaking Up Is Hard To Do,Neil Sedaka,1962-09-22,13,1
45642,Breaking Up Is Hard To Do,Neil Sedaka,1962-09-29,14,1
114578,Breaking Up Is Hard To Do,Neil Sedaka,1975-12-13,1,79
114658,Breaking Up Is Hard To Do,Neil Sedaka,1975-12-20,2,59
114733,Breaking Up Is Hard To Do,Neil Sedaka,1975-12-27,3,34
114827,Breaking Up Is Hard To Do,Neil Sedaka,1976-01-03,4,28
114921,Breaking Up Is Hard To Do,Neil Sedaka,1976-01-10,5,22
115018,Breaking Up Is Hard To Do,Neil Sedaka,1976-01-17,6,19
115116,Breaking Up Is Hard To Do,Neil Sedaka,1976-01-24,7,17
115215,Breaking Up Is Hard To Do,Neil Sedaka,1976-01-31,8,16
115309,Breaking Up Is Hard To Do,Neil Sedaka,1976-02-07,9,10
115408,Breaking Up Is Hard To Do,Neil Sedaka,1976-02-14,10,9
115507,Breaking Up Is Hard To Do,Neil Sedaka,1976-02-21,11,8
115612,Breaking Up Is Hard To Do,Neil Sedaka,1976-02-28,12,8
115717,Breaking Up Is Hard To Do,Neil Sedaka,1976-03-06,13,8
115854,Breaking Up Is Hard To Do,Neil Sedaka,1976-03-13,14,8

In [24]:
hot100_song_df[(hot100_song_df["title"]=="What About Me") & (hot100_song_df["performer"]=="Moving Pictures")]

                title        performer chart_week  wks_on_chart  peak_pos
148474  What About Me  Moving Pictures 1982-09-18             1        75
148567  What About Me  Moving Pictures 1982-09-25             2        68
148657  What About Me  Moving Pictures 1982-10-02             3        58
148754  What About Me  Moving Pictures 1982-10-09             4        55
148852  What About Me  Moving Pictures 1982-10-16             5        53
148950  What About Me  Moving Pictures 1982-10-23             6        51
149048  What About Me  Moving Pictures 1982-10-30             7        49
149146  What About Me  Moving Pictures 1982-11-06             8        47
149243  What About Me  Moving Pictures 1982-11-13             9        44
149340  What About Me  Moving Pictures 1982-11-20            10        41
149436  What About Me  Moving Pictures 1982-11-27            11        37
149536  What About Me  Moving Pictures 1982-12-04            12        37
149635  What About Me  Moving Pictures 1982-12-11            13        36
149734  What About Me  Moving Pictures 1982-12-18            14        35
149833  What About Me  Moving Pictures 1982-12-25            15        34
149933  What About Me  Moving Pictures 1983-01-01            16        34
150033  What About Me  Moving Pictures 1983-01-08            17        34
150133  What About Me  Moving Pictures 1983-01-15            18        34
150231  What About Me  Moving Pictures 1983-01-22            19        32
150329  What About Me  Moving Pictures 1983-01-29            20        30
150429  What About Me  Moving Pictures 1983-02-05            21        30
150528  What About Me  Moving Pictures 1983-02-12            22        29
150628  What About Me  Moving Pictures 1983-02-19            23        29
150772  What About Me  Moving Pictures 1983-02-26            24        29
150884  What About Me  Moving Pictures 1983-03-05            25        29
150994  What About Me  Moving Pictures 1983-03-12            26        29
184492  What About Me  Moving Pictures 1989-08-12             1        93
184579  What About Me  Moving Pictures 1989-08-19             2        80
184668  What About Me  Moving Pictures 1989-08-26             3        69
184759  What About Me  Moving Pictures 1989-09-02             4        60
184857  What About Me  Moving Pictures 1989-09-09             5        58
184952  What About Me  Moving Pictures 1989-09-16             6        53
185049  What About Me  Moving Pictures 1989-09-23             7        50
185145  What About Me  Moving Pictures 1989-09-30             8        46
185248  What About Me  Moving Pictures 1989-10-07             9        46
185351  What About Me  Moving Pictures 1989-10-14            10        46
185454  What About Me  Moving Pictures 1989-10-21            11        46
185553  What About Me  Moving Pictures 1989-10-28            12        46
185656  What About Me  Moving Pictures 1989-11-04            13        46
185765  What About Me  Moving Pictures 1989-11-11            14        46
185870  What About Me  Moving Pictures 1989-11-18            15        46
185980  What About Me  Moving Pictures 1989-11-25            16        46
186091  What About Me  Moving Pictures 1989-12-02            17        46

We see both jumps on "wks_on_chart" and	"peak_pos". 

Neil Sedaka's "Breaking Up Is Hard To Do" and Moving Pictures' "What About Me" both contradict our previous observation: they do not have memory of the past times the song is on Billboard.

More examples with memory:

In [25]:
first_week_df = hot100_chart_df[hot100_chart_df["last_week"].isna()]
first_week_df[first_week_df["current_week"]> first_week_df["peak_pos"]]

,chart_week,current_week,title,performer,last_week,peak_pos,wks_on_chart
24278,1958-08-18,79,Delicious!,Jim Backus & Friend,<NA>,66,2
24283,1958-08-18,84,Blip Blop,Bill Doggett,<NA>,82,2
24382,1958-08-25,83,Leroy,Jack Scott,<NA>,56,3
24384,1958-08-25,85,Drip Drop,The Drifters,<NA>,58,2
24577,1958-09-08,78,Blue Boy,Jim Reeves,<NA>,45,5
...,...,...,...,...,...,...,...
23985,2026-08-01,86,I Want You,Cody Johnson,<NA>,80,4
23989,2026-08-01,90,Bottom Of Your Boots,Ella Langley,<NA>,20,14
23995,2026-08-01,96,In My Room,Julia Wolf,<NA>,57,12
23996,2026-08-01,97,Empty Words,Corey Kent,<NA>,93,6
23999,2026-08-01,100,Kingdom Of Fear,Cameron Whitcomb,<NA>,94,5

In [26]:
hot100_chart_df[(hot100_chart_df["title"] == "Delicious!") & (hot100_chart_df["performer"] == "Jim Backus & Friend")]

,chart_week,current_week,title,performer,last_week,peak_pos,wks_on_chart
24065,1958-08-04,66,Delicious!,Jim Backus & Friend,<NA>,66,1
24278,1958-08-18,79,Delicious!,Jim Backus & Friend,<NA>,66,2

In [27]:
hot100_chart_df[(hot100_chart_df["title"] == "I Want You") & (hot100_chart_df["performer"] == "Cody Johnson")]

,chart_week,current_week,title,performer,last_week,peak_pos,wks_on_chart
22683,2026-05-02,84,I Want You,Cody Johnson,<NA>,84,1
23679,2026-07-11,80,I Want You,Cody Johnson,<NA>,80,2
23788,2026-07-18,89,I Want You,Cody Johnson,80,80,3
23985,2026-08-01,86,I Want You,Cody Johnson,<NA>,80,4

The examples and counterexamples are scattered throughout the years, with no clear pattern or explanation for the inconsistencies. This suggests that "peak_pos" and "wks_on_chart" are not consistently defined across the dataset and therefore need to be reengineered.

Now, check for duplicates in the table.

In [28]:
duplicates = hot100_song_df.duplicated(
    subset=["chart_week", "title", "performer"],
    keep=False
)

duplicates.any()

np.True_

In [29]:
hot100_song_df[duplicates]

,title,performer,chart_week,wks_on_chart,peak_pos
190418,Unchained Melody,The Righteous Brothers,1990-10-06,7,4
190444,Unchained Melody,The Righteous Brothers,1990-10-06,1,45
190514,Unchained Melody,The Righteous Brothers,1990-10-13,8,4
190529,Unchained Melody,The Righteous Brothers,1990-10-13,2,30
190612,Unchained Melody,The Righteous Brothers,1990-10-20,9,4
190624,Unchained Melody,The Righteous Brothers,1990-10-20,3,25
190714,Unchained Melody,The Righteous Brothers,1990-10-27,10,4
190721,Unchained Melody,The Righteous Brothers,1990-10-27,4,22
190816,Unchained Melody,The Righteous Brothers,1990-11-03,11,4
190818,Unchained Melody,The Righteous Brothers,1990-11-03,5,19
190921,Unchained Melody,The Righteous Brothers,1990-11-10,6,19
190924,Unchained Melody,The Righteous Brothers,1990-11-10,12,4
191027,Unchained Melody,The Righteous Brothers,1990-11-17,7,19
191035,Unchained Melody,The Righteous Brothers,1990-11-17,13,4
191130,Unchained Melody,The Righteous Brothers,1990-11-24,8,19
191143,Unchained Melody,The Righteous Brothers,1990-11-24,14,4
191229,Unchained Melody,The Righteous Brothers,1990-12-01,9,19
191254,Unchained Melody,The Righteous Brothers,1990-12-01,15,4
191339,Unchained Melody,The Righteous Brothers,1990-12-08,10,19
191371,Unchained Melody,The Righteous Brothers,1990-12-08,16,4
191438,Unchained Melody,The Righteous Brothers,1990-12-15,11,19
191483,Unchained Melody,The Righteous Brothers,1990-12-15,17,4
191539,Unchained Melody,The Righteous Brothers,1990-12-22,12,19
191596,Unchained Melody,The Righteous Brothers,1990-12-22,18,4
191639,Unchained Melody,The Righteous Brothers,1990-12-29,13,19
191696,Unchained Melody,The Righteous Brothers,1990-12-29,19,4

In [30]:
hot100_chart_df[(hot100_chart_df["title"] == "Unchained Melody") & (hot100_chart_df["performer"] == "The Righteous Brothers")]

,chart_week,current_week,title,performer,last_week,peak_pos,wks_on_chart
60271,1965-07-17,72,Unchained Melody,The Righteous Brothers,<NA>,72,1
60355,1965-07-24,56,Unchained Melody,The Righteous Brothers,72,56,2
60437,1965-07-31,38,Unchained Melody,The Righteous Brothers,56,38,3
60514,1965-08-07,15,Unchained Melody,The Righteous Brothers,38,15,4
60605,1965-08-14,6,Unchained Melody,The Righteous Brothers,15,6,5
60704,1965-08-21,5,Unchained Melody,The Righteous Brothers,6,5,6
60803,1965-08-28,4,Unchained Melody,The Righteous Brothers,5,4,7
60903,1965-09-04,4,Unchained Melody,The Righteous Brothers,4,4,8
61005,1965-09-11,6,Unchained Melody,The Righteous Brothers,4,4,9
61110,1965-09-18,11,Unchained Melody,The Righteous Brothers,6,4,10
61214,1965-09-25,15,Unchained Melody,The Righteous Brothers,11,4,11
61322,1965-10-02,23,Unchained Melody,The Righteous Brothers,15,4,12
61437,1965-10-09,38,Unchained Melody,The Righteous Brothers,23,4,13
189877,1990-08-25,78,Unchained Melody,The Righteous Brothers,<NA>,4,1
189955,1990-09-01,56,Unchained Melody,The Righteous Brothers,78,4,2
190036,1990-09-08,37,Unchained Melody,The Righteous Brothers,56,4,3
190129,1990-09-15,30,Unchained Melody,The Righteous Brothers,37,4,4
190223,1990-09-22,24,Unchained Melody,The Righteous Brothers,30,4,5
190318,1990-09-29,19,Unchained Melody,The Righteous Brothers,24,4,6
190418,1990-10-06,19,Unchained Melody,The Righteous Brothers,19,4,7
190444,1990-10-06,45,Unchained Melody,The Righteous Brothers,<NA>,45,1
190514,1990-10-13,15,Unchained Melody,The Righteous Brothers,19,4,8
190529,1990-10-13,30,Unchained Melody,The Righteous Brothers,45,30,2
190612,1990-10-20,13,Unchained Melody,The Righteous Brothers,15,4,9
190624,1990-10-20,25,Unchained Melody,The Righteous Brothers,30,25,3
190714,1990-10-27,15,Unchained Melody,The Righteous Brothers,13,4,10
190721,1990-10-27,22,Unchained Melody,The Righteous Brothers,25,22,4
190816,1990-11-03,17,Unchained Melody,The Righteous Brothers,15,4,11
190818,1990-11-03,19,Unchained Melody,The Righteous Brothers,22,19,5
190921,1990-11-10,22,Unchained Melody,The Righteous Brothers,19,19,6
190924,1990-11-10,25,Unchained Melody,The Righteous Brothers,17,4,12
191027,1990-11-17,28,Unchained Melody,The Righteous Brothers,22,19,7
191035,1990-11-17,36,Unchained Melody,The Righteous Brothers,25,4,13
191130,1990-11-24,31,Unchained Melody,The Righteous Brothers,28,19,8
191143,1990-11-24,44,Unchained Melody,The Righteous Brothers,36,4,14
191229,1990-12-01,30,Unchained Melody,The Righteous Brothers,31,19,9
191254,1990-12-01,55,Unchained Melody,The Righteous Brothers,44,4,15
191339,1990-12-08,40,Unchained Melody,The Righteous Brothers,30,19,10
191371,1990-12-08,72,Unchained Melody,The Righteous Brothers,55,4,16
191438,1990-12-15,39,Unchained Melody,The Righteous Brothers,40,19,11
191483,1990-12-15,84,Unchained Melody,The Righteous Brothers,72,4,17
191539,1990-12-22,40,Unchained Melody,The Righteous Brothers,39,19,12
191596,1990-12-22,97,Unchained Melody,The Righteous Brothers,84,4,18
191639,1990-12-29,40,Unchained Melody,The Righteous Brothers,40,19,13
191696,1990-12-29,97,Unchained Melody,The Righteous Brothers,97,4,19
191740,1991-01-05,41,Unchained Melody,The Righteous Brothers,40,19,14
191848,1991-01-12,49,Unchained Melody,The Righteous Brothers,41,19,15
191946,1991-01-19,47,Unchained Melody,The Righteous Brothers,49,19,16
192046,1991-01-26,47,Unchained Melody,The Righteous Brothers,47,19,17
192175,1991-02-02,76,Unchained Melody,The Righteous Brothers,47,19,18
192279,1991-02-09,80,Unchained Melody,The Righteous Brothers,76,19,19
192381,1991-02-16,82,Unchained Melody,The Righteous Brothers,80,19,20
192473,1991-02-23,74,Unchained Melody,The Righteous Brothers,82,19,21
192574,1991-03-02,75,Unchained Melody,The Righteous Brothers,74,19,22
192675,1991-03-09,76,Unchained Melody,The Righteous Brothers,75,19,23
192784,1991-03-16,85,Unchained Melody,The Righteous Brothers,76,19,24
192888,1991-03-23,89,Unchained Melody,The Righteous Brothers,85,19,25

This is actually a famous historical anomaly (1990) in the Billboard charts:

**Unchained Melody by The Righteous Brothers appears twice on the Hot 100.**

The *1965 original* used in the film Ghost, and a *newly recorded version* released by a different label following the movie's success were considered distinct recordings.

But for the purpose of lyrics finding, they shall be treated as the same song. And the song's popularity features need to be integrated.

In [31]:
hot100_song_df = hot100_song_df.sort_values(["title", "performer", "chart_week", "wks_on_chart"])
hot100_song_df

,title,performer,chart_week,wks_on_chart,peak_pos
188283,"""B"" Girls",Young And Restless,1990-05-05,1,84
188377,"""B"" Girls",Young And Restless,1990-05-12,2,78
188467,"""B"" Girls",Young And Restless,1990-05-19,3,68
188559,"""B"" Girls",Young And Restless,1990-05-26,4,60
188657,"""B"" Girls",Young And Restless,1990-06-02,5,58
...,...,...,...,...,...
244498,www.memory,Alan Jackson,2001-02-10,15,45
25965,¿Dònde Està Santa Claus? (Where Is Santa Claus?),Augie Rios,1958-12-15,1,66
26052,¿Dònde Està Santa Claus? (Where Is Santa Claus?),Augie Rios,1958-12-22,2,53
26146,¿Dònde Està Santa Claus? (Where Is Santa Claus?),Augie Rios,1958-12-29,3,47
26246,¿Dònde Està Santa Claus? (Where Is Santa Claus?),Augie Rios,1959-01-05,4,47

In [32]:
hot100_song_df = (
    hot100_song_df
    .groupby(["title", "performer", "chart_week"], as_index=False)
    .agg(
        wks_on_chart=("wks_on_chart", "max"),
        peak_pos=("peak_pos", "min"),
    )
)

In [33]:
hot100_song_df.shape

(354787, 5)

The duplicates are removed.

In [34]:
hot100_song_df[(hot100_song_df["title"] == "Unchained Melody") & (hot100_song_df["performer"] == "The Righteous Brothers")]

,title,performer,chart_week,wks_on_chart,peak_pos
317745,Unchained Melody,The Righteous Brothers,1965-07-17,1,72
317746,Unchained Melody,The Righteous Brothers,1965-07-24,2,56
317747,Unchained Melody,The Righteous Brothers,1965-07-31,3,38
317748,Unchained Melody,The Righteous Brothers,1965-08-07,4,15
317749,Unchained Melody,The Righteous Brothers,1965-08-14,5,6
317750,Unchained Melody,The Righteous Brothers,1965-08-21,6,5
317751,Unchained Melody,The Righteous Brothers,1965-08-28,7,4
317752,Unchained Melody,The Righteous Brothers,1965-09-04,8,4
317753,Unchained Melody,The Righteous Brothers,1965-09-11,9,4
317754,Unchained Melody,The Righteous Brothers,1965-09-18,10,4
317755,Unchained Melody,The Righteous Brothers,1965-09-25,11,4
317756,Unchained Melody,The Righteous Brothers,1965-10-02,12,4
317757,Unchained Melody,The Righteous Brothers,1965-10-09,13,4
317758,Unchained Melody,The Righteous Brothers,1990-08-25,1,4
317759,Unchained Melody,The Righteous Brothers,1990-09-01,2,4
317760,Unchained Melody,The Righteous Brothers,1990-09-08,3,4
317761,Unchained Melody,The Righteous Brothers,1990-09-15,4,4
317762,Unchained Melody,The Righteous Brothers,1990-09-22,5,4
317763,Unchained Melody,The Righteous Brothers,1990-09-29,6,4
317764,Unchained Melody,The Righteous Brothers,1990-10-06,7,4
317765,Unchained Melody,The Righteous Brothers,1990-10-13,8,4
317766,Unchained Melody,The Righteous Brothers,1990-10-20,9,4
317767,Unchained Melody,The Righteous Brothers,1990-10-27,10,4
317768,Unchained Melody,The Righteous Brothers,1990-11-03,11,4
317769,Unchained Melody,The Righteous Brothers,1990-11-10,12,4
317770,Unchained Melody,The Righteous Brothers,1990-11-17,13,4
317771,Unchained Melody,The Righteous Brothers,1990-11-24,14,4
317772,Unchained Melody,The Righteous Brothers,1990-12-01,15,4
317773,Unchained Melody,The Righteous Brothers,1990-12-08,16,4
317774,Unchained Melody,The Righteous Brothers,1990-12-15,17,4
317775,Unchained Melody,The Righteous Brothers,1990-12-22,18,4
317776,Unchained Melody,The Righteous Brothers,1990-12-29,19,4
317777,Unchained Melody,The Righteous Brothers,1991-01-05,14,19
317778,Unchained Melody,The Righteous Brothers,1991-01-12,15,19
317779,Unchained Melody,The Righteous Brothers,1991-01-19,16,19
317780,Unchained Melody,The Righteous Brothers,1991-01-26,17,19
317781,Unchained Melody,The Righteous Brothers,1991-02-02,18,19
317782,Unchained Melody,The Righteous Brothers,1991-02-09,19,19
317783,Unchained Melody,The Righteous Brothers,1991-02-16,20,19
317784,Unchained Melody,The Righteous Brothers,1991-02-23,21,19
317785,Unchained Melody,The Righteous Brothers,1991-03-02,22,19
317786,Unchained Melody,The Righteous Brothers,1991-03-09,23,19
317787,Unchained Melody,The Righteous Brothers,1991-03-16,24,19
317788,Unchained Melody,The Righteous Brothers,1991-03-23,25,19

But problems presisted:
* from 1965-10-09 to 1990-08-25, "wks_on_chart" jumps but "peak_pos" does not.
* from 1990-12-29 to 1991-01-05, "wks_on_chart" jumps from 19 to 14
* from 1990-12-29 to 1991-01-05, "peak_pos" jumps from 4 to 19

In this case, it is better to understand both "wks_on_chart" and "peak_pos" to preserve memory, so each of them can be resolved with cumcount() and cummin(). 

This method can actually make the meanings of "wks_on_chart" and "peak_pos" consistent (with past memory) across the entire DataFrame.

In [35]:
# Make sure rows are chronological within each song
hot100_song_df = hot100_song_df.sort_values(["title", "performer", "chart_week"])

# Rebuild weeks on chart: 1, 2, 3, ...
hot100_song_df["wks_on_chart"] = hot100_song_df.groupby(["title", "performer"]).cumcount() + 1

# Rebuild peak position: best position achieved up through that week
hot100_song_df["peak_pos"] = hot100_song_df.groupby(["title", "performer"])["peak_pos"].cummin()

Double check the previous counter examples:

In [36]:
hot100_song_df[(hot100_song_df["title"] == "I Want You") & (hot100_song_df["performer"] == "Cody Johnson")]

             title     performer chart_week  wks_on_chart  peak_pos
140104  I Want You  Cody Johnson 2026-05-02             1        84
140105  I Want You  Cody Johnson 2026-07-11             2        80
140106  I Want You  Cody Johnson 2026-07-18             3        80
140107  I Want You  Cody Johnson 2026-08-01             4        80

In [37]:
hot100_song_df[(hot100_song_df["title"] == "Delicious!") & (hot100_song_df["performer"] == "Jim Backus & Friend")]

            title            performer chart_week  wks_on_chart  peak_pos
64841  Delicious!  Jim Backus & Friend 1958-08-04             1        66
64842  Delicious!  Jim Backus & Friend 1958-08-18             2        66

In [38]:
hot100_song_df[(hot100_song_df["title"] == "Unchained Melody") & (hot100_song_df["performer"] == "The Righteous Brothers")]

,title,performer,chart_week,wks_on_chart,peak_pos
317745,Unchained Melody,The Righteous Brothers,1965-07-17,1,72
317746,Unchained Melody,The Righteous Brothers,1965-07-24,2,56
317747,Unchained Melody,The Righteous Brothers,1965-07-31,3,38
317748,Unchained Melody,The Righteous Brothers,1965-08-07,4,15
317749,Unchained Melody,The Righteous Brothers,1965-08-14,5,6
317750,Unchained Melody,The Righteous Brothers,1965-08-21,6,5
317751,Unchained Melody,The Righteous Brothers,1965-08-28,7,4
317752,Unchained Melody,The Righteous Brothers,1965-09-04,8,4
317753,Unchained Melody,The Righteous Brothers,1965-09-11,9,4
317754,Unchained Melody,The Righteous Brothers,1965-09-18,10,4
317755,Unchained Melody,The Righteous Brothers,1965-09-25,11,4
317756,Unchained Melody,The Righteous Brothers,1965-10-02,12,4
317757,Unchained Melody,The Righteous Brothers,1965-10-09,13,4
317758,Unchained Melody,The Righteous Brothers,1990-08-25,14,4
317759,Unchained Melody,The Righteous Brothers,1990-09-01,15,4
317760,Unchained Melody,The Righteous Brothers,1990-09-08,16,4
317761,Unchained Melody,The Righteous Brothers,1990-09-15,17,4
317762,Unchained Melody,The Righteous Brothers,1990-09-22,18,4
317763,Unchained Melody,The Righteous Brothers,1990-09-29,19,4
317764,Unchained Melody,The Righteous Brothers,1990-10-06,20,4
317765,Unchained Melody,The Righteous Brothers,1990-10-13,21,4
317766,Unchained Melody,The Righteous Brothers,1990-10-20,22,4
317767,Unchained Melody,The Righteous Brothers,1990-10-27,23,4
317768,Unchained Melody,The Righteous Brothers,1990-11-03,24,4
317769,Unchained Melody,The Righteous Brothers,1990-11-10,25,4
317770,Unchained Melody,The Righteous Brothers,1990-11-17,26,4
317771,Unchained Melody,The Righteous Brothers,1990-11-24,27,4
317772,Unchained Melody,The Righteous Brothers,1990-12-01,28,4
317773,Unchained Melody,The Righteous Brothers,1990-12-08,29,4
317774,Unchained Melody,The Righteous Brothers,1990-12-15,30,4
317775,Unchained Melody,The Righteous Brothers,1990-12-22,31,4
317776,Unchained Melody,The Righteous Brothers,1990-12-29,32,4
317777,Unchained Melody,The Righteous Brothers,1991-01-05,33,4
317778,Unchained Melody,The Righteous Brothers,1991-01-12,34,4
317779,Unchained Melody,The Righteous Brothers,1991-01-19,35,4
317780,Unchained Melody,The Righteous Brothers,1991-01-26,36,4
317781,Unchained Melody,The Righteous Brothers,1991-02-02,37,4
317782,Unchained Melody,The Righteous Brothers,1991-02-09,38,4
317783,Unchained Melody,The Righteous Brothers,1991-02-16,39,4
317784,Unchained Melody,The Righteous Brothers,1991-02-23,40,4
317785,Unchained Melody,The Righteous Brothers,1991-03-02,41,4
317786,Unchained Melody,The Righteous Brothers,1991-03-09,42,4
317787,Unchained Melody,The Righteous Brothers,1991-03-16,43,4
317788,Unchained Melody,The Righteous Brothers,1991-03-23,44,4

Great!

For the purpose of lyrics finding, "title" and "performer" are enough to define a song. All other attributes ("chart_week", "wks_on_chart", "peak_pos") just indicate a song's popularity. 

Here, I would like to integrate those attributes and generate popularity features for each song:

* **chart_weeks**: a list of all weeks on chart
* **periods_on_chart (not for MVP now)**: number of distinct periods in which a song appears on the Hot 100. A re-entry after only a few weeks may simply reflect a brief interruption, while a return after a longer absence can indicate renewed popularity. Need info from hot100_chart_df.
* **wks_on_chart**: the total number of weeks on chart
* **peak_pos**: the best ever position on chart

In [39]:
hot100_song_df = (
    hot100_song_df
    .sort_values(["title", "performer", "chart_week"])
    .groupby(["title", "performer"], as_index=False)
    .agg(
        chart_weeks=("chart_week", list), # ordered from earlier sort_values
        wks_on_chart=("wks_on_chart", "max"),
        peak_pos=("peak_pos", "min"),
    )
)

In [40]:
hot100_song_df

,title,performer,chart_weeks,wks_on_chart,peak_pos
0,"""B"" Girls",Young And Restless,"[1990-05-05 00:00:00, 1990-05-12 00:00:00, 199...",15,54
1,"""Cherry Cherry"" from Hot August Night",Neil Diamond,"[1973-03-17 00:00:00, 1973-03-24 00:00:00, 197...",10,31
2,"""Having A Party"" Medley",The Ovations (Featuring Louis Williams),"[1973-10-13 00:00:00, 1973-10-20 00:00:00, 197...",9,56
3,"""Joy"" Pt. I",Isaac Hayes,"[1973-12-22 00:00:00, 1973-12-29 00:00:00, 197...",9,30
4,"""Roots"" Medley",Quincy Jones,"[1977-03-05 00:00:00, 1977-03-12 00:00:00, 197...",7,57
...,...,...,...,...,...
32671,wgft,Gunna Featuring Burna Boy,"[2025-08-23 00:00:00, 2025-08-30 00:00:00, 202...",26,16
32672,whoa (mind in awe),XXXTENTACION,"[2018-12-22 00:00:00, 2018-12-29 00:00:00, 201...",3,37
32673,whoknows,Musiq,"[2004-04-24 00:00:00, 2004-05-01 00:00:00, 200...",13,65
32674,www.memory,Alan Jackson,"[2000-11-04 00:00:00, 2000-11-11 00:00:00, 200...",15,45
32675,¿Dònde Està Santa Claus? (Where Is Santa Claus?),Augie Rios,"[1958-12-15 00:00:00, 1958-12-22 00:00:00, 195...",4,47

In [41]:
hot100_song_df.shape

(32676, 5)

In [42]:
hot100_song_df.to_parquet("../data/hot-100-song_current.parquet", index=False)

---

Filter the data set to only contarin Billboard Hot 100 from START_WEEK to END_WEEK.

In [43]:
START_WEEK = pd.Timestamp("1958-08-04")
END_WEEK = pd.Timestamp("2026-08-01")

In [44]:
filtered_hot100_song_df = hot100_song_df[
    (hot100_song_df["chart_weeks"].str[0] >= START_WEEK) &
    (hot100_song_df["chart_weeks"].str[-1] < END_WEEK)
]

In [45]:
filtered_hot100_song_df.shape

(32576, 5)

In [46]:
filtered_hot100_song_df

,title,performer,chart_weeks,wks_on_chart,peak_pos
0,"""B"" Girls",Young And Restless,"[1990-05-05 00:00:00, 1990-05-12 00:00:00, 199...",15,54
1,"""Cherry Cherry"" from Hot August Night",Neil Diamond,"[1973-03-17 00:00:00, 1973-03-24 00:00:00, 197...",10,31
2,"""Having A Party"" Medley",The Ovations (Featuring Louis Williams),"[1973-10-13 00:00:00, 1973-10-20 00:00:00, 197...",9,56
3,"""Joy"" Pt. I",Isaac Hayes,"[1973-12-22 00:00:00, 1973-12-29 00:00:00, 197...",9,30
4,"""Roots"" Medley",Quincy Jones,"[1977-03-05 00:00:00, 1977-03-12 00:00:00, 197...",7,57
...,...,...,...,...,...
32671,wgft,Gunna Featuring Burna Boy,"[2025-08-23 00:00:00, 2025-08-30 00:00:00, 202...",26,16
32672,whoa (mind in awe),XXXTENTACION,"[2018-12-22 00:00:00, 2018-12-29 00:00:00, 201...",3,37
32673,whoknows,Musiq,"[2004-04-24 00:00:00, 2004-05-01 00:00:00, 200...",13,65
32674,www.memory,Alan Jackson,"[2000-11-04 00:00:00, 2000-11-11 00:00:00, 200...",15,45
32675,¿Dònde Està Santa Claus? (Where Is Santa Claus?),Augie Rios,"[1958-12-15 00:00:00, 1958-12-22 00:00:00, 195...",4,47

In [47]:

filtered_hot100_song_df.to_parquet(f"../data/hot-100-song_{START_WEEK:%Y%m%d}_{END_WEEK:%Y%m%d}.parquet", index=False)

---