In [1]:
# autoreload every imported modules if their source files have changed.
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
from src.config import HOT100_LYRICS_OUTPUT
filtered_hot100_lyrics_df = pd.read_parquet(HOT100_LYRICS_OUTPUT)

In [3]:
filtered_hot100_lyrics_df

,title,performer,chart_weeks,wks_on_chart,peak_pos,plain_lyrics
0,$ex Appeal,Baby Keem Featuring Too $hort,[2026-03-07],1,69,"(Play with me, play with me)\n(Play with me, p..."
1,'98 Braves,Morgan Wallen,"[2023-03-18, 2023-03-25, 2023-04-01, 2023-04-0...",7,27,I remember sittin' at that house\nLivin' room ...
2,'Til You Can't,Cody Johnson,"[2021-10-23, 2021-10-30, 2021-11-06, 2022-01-0...",29,18,You can tell your old man\nYou'll do some larg...
3,'Tis The Damn Season,Taylor Swift,"[2020-12-26, 2021-01-02]",2,39,If I wanted to know who you were hanging with\...
4,(There's No Place Like) Home For The Holidays ...,Perry Como With Mitchell Ayers And His Orchestra,[2024-01-06],1,50,"Oh, there's no place like home for the holiday..."
...,...,...,...,...,...,...
4079,pov,Ariana Grande,"[2020-11-14, 2020-11-21, 2020-11-28, 2020-12-0...",20,27,It's like you got superpowers\nTurn my minutes...
4080,punchin'.the.clock,J. Cole,"[2021-05-29, 2021-06-05]",2,20,It ain't nothin' I want more\nAin't nothin' I ...
4081,thanK you aIMee,Taylor Swift,"[2024-05-04, 2024-05-11, 2024-05-18]",3,23,"When I picture my hometown\nThere's a bronze, ..."
4082,the.climb.back,J. Cole,"[2021-05-29, 2021-06-05]",2,25,Are you doin' this work to facilitate growth o...
4083,wgft,Gunna Featuring Burna Boy,"[2025-08-23, 2025-08-30, 2025-09-06, 2025-09-1...",26,16,It's so amazin' what we've done\nRidin' the wa...

In [4]:
lyrics4083 = filtered_hot100_lyrics_df.at[4083, "plain_lyrics"]
lyrics4083

"It's so amazin' what we've done\nRidin' the wave of love as one\nTakin' our time to feel the love\nWe are all stars under the sun\n\nWe gettin' fucked tonight, we gettin' fucked tonight\nWe gettin' fucked tonight, we gettin' fucked tonight\nWe gettin' fucked tonight, we gettin' fucked tonight (run that back, Turbo)\nWe gettin' fucked tonight, we gettin' fucked tonight\n\nWe gettin' fucked tonight, who gettin' fucked tonight?\nYou gettin' fucked tonight, she gettin' fucked tonight\nShe gettin' fucked tonight, she gettin' fucked tonight\nShe gettin' fucked tonight, she gettin' fucked tonight\n\nStop callin' her phone, she gettin' fucked tonight\nBlowin' down her line, you the buster type\nKnowin' that you lyin', we don't go for the hype (yeah)\nCatch 'em from behind, niggas know I'ma snipe (yeah)\n\nSuck it when I drive, baby know what I like (yeah)\nSpread that pussy wide, let me go for a dive (yeah)\n(It's so amazin' what we've done)\n(Ridin' the wave of love as one) who gettin' fucked tonight?\n(Takin' our time to feel the love)\n(We are all stars under the sun) you gettin' fucked tonight\n\nBae, you wit' it tonight? I'll pay whatever the price\nI'll knock her down, I'ma strike, I wanna fit it inside\nGettin' with me is enticin', her pussy is my vice\nI see you, we gon' fight, you gettin' fucked tonight\n\nIt's so amazin' what we've done\nRidin' the wave of love as one (who gettin' fucked tonight?)\nTakin' our time to feel the love\nWe are all stars under the sun\n\nWe gettin' fucked tonight, we gettin' fucked tonight\nWe gettin' fucked tonight, we gettin' fucked tonight\nWe gettin' fucked tonight, we gettin' fucked tonight\nWe gettin' fucked tonight, we gettin' fucked tonight\n\nDon't bring your friend if it ain't gonna be a threesome\nWon't pretend, ain't gonna lie, I'm tryna freak somethin'\nAnd I see you a sweet one, you a freak, you's a demon\nAnd I'm just one more body, I don't really mean nothin', mm, mm\n\nI dey control, whoa-whoa, call me remote\nIf I push one button, it's off with your clothes (it's so amazin' what we've done)\nIf I don't do nothin', I do the most (ridin' the wave of love as one)\n(Takin' our time to feel the love) I wanna know\n(We are all stars under the sun) who gettin' fucked tonight?\n\nWe gettin' fucked tonight, we gettin' fucked tonight\nWe gettin' fucked tonight (uh), we gettin' fucked tonight (oh)\nWe gettin' fucked tonight (uh), we gettin' fucked tonight (uh)\nWe gettin' fucked tonight (uh), we gettin' fucked tonight\n\nIt's so amazin' what we've done\nRidin' the wave of love as one\nTakin' our time to feel the love\nWe are all stars under the sun\n\nWe gettin' fucked tonight, we gettin' fucked tonight\nWe gettin' fucked tonight, we gettin' fucked tonight\nWe gettin' fucked tonight, we gettin' fucked tonight\nWe gettin' fucked tonight, we gettin' fucked tonight (uh, ooh, yeah, oh)"

In [5]:
print(lyrics4083)

It's so amazin' what we've done
Ridin' the wave of love as one
Takin' our time to feel the love
We are all stars under the sun

We gettin' fucked tonight, we gettin' fucked tonight
We gettin' fucked tonight, we gettin' fucked tonight
We gettin' fucked tonight, we gettin' fucked tonight (run that back, Turbo)
We gettin' fucked tonight, we gettin' fucked tonight

We gettin' fucked tonight, who gettin' fucked tonight?
You gettin' fucked tonight, she gettin' fucked tonight
She gettin' fucked tonight, she gettin' fucked tonight
She gettin' fucked tonight, she gettin' fucked tonight

Stop callin' her phone, she gettin' fucked tonight
Blowin' down her line, you the buster type
Knowin' that you lyin', we don't go for the hype (yeah)
Catch 'em from behind, niggas know I'ma snipe (yeah)

Suck it when I drive, baby know what I like (yeah)
Spread that pussy wide, let me go for a dive (yeah)
(It's so amazin' what we've done)
(Ridin' the wave of love as one) who gettin' fucked tonight?
(Takin' our time to feel the love)
(We are all stars under the sun) you gettin' fucked tonight

Bae, you wit' it tonight? I'll pay whatever the price
I'll knock her down, I'ma strike, I wanna fit it inside
Gettin' with me is enticin', her pussy is my vice
I see you, we gon' fight, you gettin' fucked tonight

It's so amazin' what we've done
Ridin' the wave of love as one (who gettin' fucked tonight?)
Takin' our time to feel the love
We are all stars under the sun

We gettin' fucked tonight, we gettin' fucked tonight
We gettin' fucked tonight, we gettin' fucked tonight
We gettin' fucked tonight, we gettin' fucked tonight
We gettin' fucked tonight, we gettin' fucked tonight

Don't bring your friend if it ain't gonna be a threesome
Won't pretend, ain't gonna lie, I'm tryna freak somethin'
And I see you a sweet one, you a freak, you's a demon
And I'm just one more body, I don't really mean nothin', mm, mm

I dey control, whoa-whoa, call me remote
If I push one button, it's off with your clothes (it's so amazin' what we've done)
If I don't do nothin', I do the most (ridin' the wave of love as one)
(Takin' our time to feel the love) I wanna know
(We are all stars under the sun) who gettin' fucked tonight?

We gettin' fucked tonight, we gettin' fucked tonight
We gettin' fucked tonight (uh), we gettin' fucked tonight (oh)
We gettin' fucked tonight (uh), we gettin' fucked tonight (uh)
We gettin' fucked tonight (uh), we gettin' fucked tonight

It's so amazin' what we've done
Ridin' the wave of love as one
Takin' our time to feel the love
We are all stars under the sun

We gettin' fucked tonight, we gettin' fucked tonight
We gettin' fucked tonight, we gettin' fucked tonight
We gettin' fucked tonight, we gettin' fucked tonight
We gettin' fucked tonight, we gettin' fucked tonight (uh, ooh, yeah, oh)

In [6]:
from src.chunk_lyrics import chunk_song_lyrics
sections4083, num_lines4083 = chunk_song_lyrics(lyrics4083)
num_lines4083

[4, 4, 4, 4, 6, 4, 4, 4, 4, 5, 4, 4, 4]

In [7]:
from src.chunk_lyrics import MIN_LINES_PER_CHUNK
sum(num < MIN_LINES_PER_CHUNK for num in num_lines4083)

0

In [8]:
lyrics0 = filtered_hot100_lyrics_df.at[0, "plain_lyrics"]
lyrics0

'(Play with me, play with me)\n(Play with me, pla-play with me) up all night, baby\n(Play with me, play with me)\n(Play with me, pla-play with me) it\'s $hort Dog\n\n(Play with me, play with me)\n(Play with me, pla-play with me) bright lights\n(Play with me, play with me)\n(Play with me, pla-play) Ca$ino\n\nI\'m in the mood (I\'m in the mood), we in Miami (Miami)\nI met a freak (I met a freak) from Cincinnati (from Cincinnati)\nShe\'s five foot four, Margiela Tabis\nUnder the hood (under the hood), she got no panties (bitch)\nHer body smooth (her body smooth), I know she want me\nParty animal, I\'m in the moment and I\'m irrational\nSpur of the moment, she get magical\n\nToo much sex appeal (ah)\nToo much sex appeal (ah)\nToo much sex appeal\nToo much sex appeal (ah)\n\nToo much sex appeal (ah)\nToo much sex appeal (ah)\nI want you, can\'t you tell?\nToo much sex appeal (ah)\nTell me (yeah)\n\nLove the way you talk, you drop that amazin\' (amazin\')\nFirst name basis, call me, "Baby" (uh, baby)\nIt\'s some bitches here that might need savin\' (uh-huh, savin\')\nIt\'s some niggas here blowin\' all they savings (savings)\n\nWon\'t you just cancel the mornin\'?\nYou gone and I\'m on it, whenever you want it\nSwap it to the side, missionary get borin\'\nWhen I\'m with this bitch, I feel every endorphin\n\nShe got sex appeal\n\'Cause she only like sex and pills\nLate night, come chill, babe\nReason why I can\'t sit still, babe\n\nShe got sex appeal\nShe only like sex and pills\nLate night, come chill, babe\nReason why I can\'t sit still, babe (on God)\n\nIt\'s Too $hort, I be out here winnin\' with the gang\nHad that lil\' church girl sinnin\'\nYou\'ll never get her back from me\nWhen she jumped off the porch, it had to be a real P\n\nAll in her ear\nYou a lucky ass bitch if you end up here with me (bitch)\n\'Cause I don\'t waste no time\nAll these hos out here wish they was mine, but fuck them (fuck)\n\nI don\'t want none\nI\'m tryna see where this new bitch come from (where you from, bitch?)\nI heard about it when she first touched down\nNew bad lil\' bitch in the town (bitch)\n\nLookin\' like she know how to get it\nMake a square nigga wanna hit it (on God)\nYou fallin\' in love with these women\nBut they fallin\' in love with this pimpin\'\n\nToo much sex appeal (ah)\nToo much sex appeal (ah)\nToo much sex appeal\nToo much sex appeal (ah)\n\nToo much sex appeal (ah)\nToo much sex appeal (ah)\nI want you, can\'t you tell?\nToo much sex appeal (ah)\nTell me (yeah)\n\nLa, la-la\nLa, la-la'

In [9]:
print(lyrics0)

(Play with me, play with me)
(Play with me, pla-play with me) up all night, baby
(Play with me, play with me)
(Play with me, pla-play with me) it's $hort Dog

(Play with me, play with me)
(Play with me, pla-play with me) bright lights
(Play with me, play with me)
(Play with me, pla-play) Ca$ino

I'm in the mood (I'm in the mood), we in Miami (Miami)
I met a freak (I met a freak) from Cincinnati (from Cincinnati)
She's five foot four, Margiela Tabis
Under the hood (under the hood), she got no panties (bitch)
Her body smooth (her body smooth), I know she want me
Party animal, I'm in the moment and I'm irrational
Spur of the moment, she get magical

Too much sex appeal (ah)
Too much sex appeal (ah)
Too much sex appeal
Too much sex appeal (ah)

Too much sex appeal (ah)
Too much sex appeal (ah)
I want you, can't you tell?
Too much sex appeal (ah)
Tell me (yeah)

Love the way you talk, you drop that amazin' (amazin')
First name basis, call me, "Baby" (uh, baby)
It's some bitches here that might need savin' (uh-huh, savin')
It's some niggas here blowin' all they savings (savings)

Won't you just cancel the mornin'?
You gone and I'm on it, whenever you want it
Swap it to the side, missionary get borin'
When I'm with this bitch, I feel every endorphin

She got sex appeal
'Cause she only like sex and pills
Late night, come chill, babe
Reason why I can't sit still, babe

She got sex appeal
She only like sex and pills
Late night, come chill, babe
Reason why I can't sit still, babe (on God)

It's Too $hort, I be out here winnin' with the gang
Had that lil' church girl sinnin'
You'll never get her back from me
When she jumped off the porch, it had to be a real P

All in her ear
You a lucky ass bitch if you end up here with me (bitch)
'Cause I don't waste no time
All these hos out here wish they was mine, but fuck them (fuck)

I don't want none
I'm tryna see where this new bitch come from (where you from, bitch?)
I heard about it when she first touched down
New bad lil' bitch in the town (bitch)

Lookin' like she know how to get it
Make a square nigga wanna hit it (on God)
You fallin' in love with these women
But they fallin' in love with this pimpin'

Too much sex appeal (ah)
Too much sex appeal (ah)
Too much sex appeal
Too much sex appeal (ah)

Too much sex appeal (ah)
Too much sex appeal (ah)
I want you, can't you tell?
Too much sex appeal (ah)
Tell me (yeah)

La, la-la
La, la-la

Observation: there are occasions where the lyrics section is too short, which does not make any sence for later vector search. Consider merge short sections with others.

In [10]:
sections0, num_lines0 = chunk_song_lyrics(lyrics0)
num_lines0

[4, 4, 7, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 2]

In [11]:
indices = [
    i for i, n in enumerate(num_lines0)
    if n < MIN_LINES_PER_CHUNK
]
indices

[15]

In [12]:
print(sections0[15])

La, la-la
La, la-la

In [13]:
from src.chunk_lyrics import merge_short_sections
sections0, num_lines0 = merge_short_sections(sections0, num_lines0)
num_lines0

[4, 4, 7, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 7]

In [14]:
indices = [
    i for i, n in enumerate(num_lines0)
    if n < MIN_LINES_PER_CHUNK
]
indices

[]

In [15]:
print(sections0[-1])

Too much sex appeal (ah)
Too much sex appeal (ah)
I want you, can't you tell?
Too much sex appeal (ah)
Tell me (yeah)

La, la-la
La, la-la

Problem fixed!

---

In [133]:
from src.chunk_lyrics import build_chunk_documents
documents = build_chunk_documents(filtered_hot100_lyrics_df)

0
(There's No Place Like) Home For The Holidays (1959)
Perry Como With Mitchell Ayers And His Orchestra
1
1 Step Forward, 3 Steps Back
Olivia Rodrigo
2
2 Be Loved (Am I Ready)
Lizzo
3
39 Intro
J. Cole
4
3D
Jung Kook & Jack Harlow
5
3am
Loe Shimmy & Don Toliver
6
5 Dollar Pony Rides
Mac Miller
7
54321
Offset
8
AP
Pop Smoke
9
Ace Trumpets
Clipse
10
Actually Romantic
Taylor Swift
11
After A Few
Travis Denning
12
Ain't Always The Cowboy
Jon Pardi
13
All I Did Was Dream of You
beabadoobee Featuring The Marias
14
All Night Parking (Interlude)
Adele With Erroll Garner
15
All To Myself
Future, Metro Boomin & The Weeknd
16
Alliigator Tears
Beyonce
17
Almost Maybes
Jordan Davis
18
America Has A Problem
Beyonce
19
Angels Don't Always Have Wings
Thomas Rhett
20
Another Day
Kid Cudi
21
Anything But Love
Tate McRae
22
Aperture
Harry Styles
23
Are You Even Real
Teddy Swims & GIVEON
24
At My Purest
Gunna Featuring Offset
25
Attention
Doja Cat
26
BLAME IT ON BABY
DaBaby
27
Back On My BS
BigXthaPlug
28
Back Then Right Now
Tyler Hubbard
29
BackOutsideBoyz
Drake
30
Beautiful Trip
Kid Cudi
31
Beep Beep
Nicki Minaj
32
Before Fajr
Lil Durk
33
Bells
Lil Wayne
34
Big Poe
Tyler, the Creator Featuring Sk8brd
35
Big, Big Plans
Chris Lane
36
Bigger Than Life
Lil Uzi Vert
37
Blame It On You
Jason Aldean
38
Blow
Moneybagg Yo
39
Born With A Beer In My Hand
Morgan Wallen
40
Box Of Churches
Pooh Shiesty Featuring 21 Savage
41
Boyfriends
Harry Styles
42
Brainwashed
Tom MacDonald
43
Bread & Butter
Gunna
44
Burglars & Murderers
Lil Durk Featuring EST Gee
45
Bury Me In Georgia
Kane Brown
46
But I Got A Beer In My Hand
Luke Bryan
47
CAN'T STOP
DaBaby
48
Call Back
Don Toliver
49
Calling My Name
Drake
50
Cannonball
Zach Bryan
51
Ceremony
Stray Kids
52
Chains Of Love
Charli xcx
53
Charlie
Tom MacDonald
54
Chicago Freestyle
Drake Featuring Giveon
55
Chill Bae
Lil Uzi Vert
56
Circadian Rhythm
Drake
57
Cold As You
Luke Combs
58
Come Back As A Country Boy
Blake Shelton
59
Come Over
BTS
60
Cool Again
Kane Brown
61
Cowboy Like Me
Taylor Swift
62
Cowgirl
Parmalee
63
Crush Em
Lil Uzi Vert
64
DJ Play A Christmas Song
Cher
65
Damaged
Kid Cudi
66
Dangerous
Sleep Token
67
Die Trying
PARTYNEXTDOOR, Drake & Yebba
68
Do It
Stray Kids
69
Done
Chris Janson
70
Dont Let Me Go
mgk
71
Down Home
Jimmie Allen
72
Drinking Alone
Carrie Underwood
73
Dying Man
Morgan Wallen
74
EOO
Bad Bunny
75
Efecto
Bad Bunny
76
Eldest Daughter
Taylor Swift
77
Elizabeth Taylor
Taylor Swift
78
Envolver
Anitta
79
Everything She Ain't
Hailey Whitters
80
Expensive Pain
Meek Mill
81
Eye To Eye
Future
82
Eyes Closed
JISOO & ZAYN
83
Father Figure
Taylor Swift
84
Fear And Friday's (Poem)
Zach Bryan
85
Fifteen (Taylor's Version)
Taylor Swift
86
Fix'n To Break
Bailey Zimmerman
87
Flamenco
Beyonce
88
Free Mind
Tems
89
Fucking Fans
Drake
90
Fuk Sumn
¥$: Kanye West & Ty Dolla $ign
91
Funeral
Lil Wayne
92
GNX
Kendrick Lamar Featuring Hitta J3, YoungThreat & Peysoh
93
Get Into It (Yuh)
Doja Cat
94
Gimmick
Gunna
95
Give Me A Reason
NF
96
Glory Voice Memo
Justin Bieber
97
Go2DaMoon
Playboi Carti Featuring Kanye West
98
God Was Showing Off
Bruno Mars
99
God Whispered Your Name
Keith Urban
100
Gone Girl
SZA
101
Good (Don't Die)
¥$: Kanye West & Ty Dolla $ign
102
Great Gatsby
Rod Wave
103
Half Of Me
Thomas Rhett Featuring Riley Green
104
Happy Does
Kenny Chesney
105
Harlem Shake
Future Featuring Young Thug
106
Hate Me
Lil Yachty & ian
107
Heal Your Heart (Interlude)
Brent Faiyaz
108
Heavens To Betsy
Jackson Dean
109
Hell Of A View
Eric Church
110
Highs And Lows
Ye
111
Holiday Road
Kesha
112
Honey
Taylor Swift
113
Hope That's True
Morgan Wallen
114
Houdini
Eminem
115
How Do I Make You Love Me?
The Weeknd
116
How The Game Go
Rod Wave
117
I Bet You Think About Me (Taylor's Version) (From The Vault)
Taylor Swift Featuring Chris Stapleton
118
I Heard
YoungBoy Never Broke Again
119
I Killed You
Tyler, The Creator
120
I Know
Polo G
121
I Thought I Saw Your Face Today
She & Him
122
I Was On A Boat That Day
Old Dominion
123
If I Could
Future
124
In Your Fantasy
ATEEZ
125
Infinite Baths
Sleep Token
126
Insecurities
Lil Baby
127
It Won't Be Long
George Birge
128
Ivy
Taylor Swift
129
Just About Over You
Priscilla Block
130
Killin' It Girl
j-hope & GloRilla
131
King Carter
Lil Wayne
132
La Droga
Bad Bunny
133
La Mudanza
Bad Bunny
134
La Perla
ROSALIA & Yahritza y Su Esencia
135
Landed
Drake
136
Lasers
PARTYNEXTDOOR & Drake
137
Last Christmas
Lauren Spencer-Smith
138
Leave You Alone
Kane Brown
139
Let Alone The One You Love
Olivia Dean
140
Like Animals
BTS
141
Like I Love Country Music
Kane Brown
142
Lost My Dog
Future
143
Love Language
Ariana Grande
144
Love Lost
Mac Miller
145
Mad Woman
Taylor Swift
146
Made My Hoe Faint
Future
147
Martin & Gina
Polo G
148
Miami
Morgan Wallen
149
Minimum Wage
Blake Shelton
150
Money Over Everything
Future
151
Moonwalking In Calabasas
DDG
152
My Little Love
Adele
153
My Time
BTS
154
New Truck
Dylan Scott
155
Nice To Each Other
Olivia Dean
156
No Good Deed
Cynthia Erivo
157
No Trespassing
A$AP Rocky
158
No Weakness
Rod Wave
159
Nobody's Girl
Tate McRae
160
Noid
Tyler, The Creator
161
Notice Me
SZA
162
Nuevayol
Bad Bunny
163
OPM Babi
Playboi Carti
164
On My Soul
Bruno Mars
165
On Time
Metro Boomin & John Legend
166
Order Of Protection
A$AP Rocky
167
Pain Away
Meek Mill Featuring Lil Durk
168
Pass You By
Rod Wave
169
Passenger
Alex Warren
170
Past Self
Sleep Token
171
Permission To Dance
BTS
172
Pick Me Up
Gabby Barrett
173
Players
Coi Leray
174
Plutoski
Future
175
Preacher Man
Ye
176
Provider
Sleep Token
177
Purple Lace Bra
Tate McRae
178
Radio
Future
179
Rap Freaks
Yung Miami
180
Red Button
Drake
181
Rockin' Around The Christmas Tree
Justin Bieber
182
Ruin The Friendship
Taylor Swift
183
Run BTS
BTS
184
Savior
Kendrick Lamar, Baby Keem, & Sam Dew
185
Screw Juice
Juice WRLD
186
Search & Rescue
Drake
187
She's Somebody's Daughter (Reimagined)
Drew Baldridge
188
Show Of Hands
Future, Metro Boomin & A$AP Rocky
189
Silent Treatment
Freya Skye
190
Smurk Carter
Lil Durk
191
Some Girls
Jameson Rodgers
192
Somebody Loves Me
PARTYNEXTDOOR, Drake & Cash Cobain
193
Spider-Man Superman
PARTYNEXTDOOR & Drake
194
Spin You Around (1/24)
Morgan Wallen
195
Squabble Up
Kendrick Lamar
196
Standing Room Only
Tim McGraw
197
Stars Like Confetti
Dustin Lynch
198
Stepdad
Eminem
199
Steve's Lava Chicken
Jack Black
200
Sticky
Drake
201
Stone Rolling
Rod Wave
202
Strangers By Nature
Adele
203
Sum 2 Prove
Lil Baby
204
Summer Renaissance
Beyonce
205
Sympathy Is A Knife
Charli xcx Featuring Ariana Grande
206
TMU
Don Toliver
207
Take Her Home
Kenny Chesney
208
Take Your Mask Off
Tyler, The Creator Featuring Daniel Caesar & Latoiya Williams
209
Tequila Little Time
Jon Pardi
210
The Girl In The Bubble
Ariana Grande
211
The Last Great American Dynasty
Taylor Swift
212
The Life Of A Showgirl
Taylor Swift Featuring Sabrina Carpenter
213
The Man He Sees In Me
Luke Combs
214
The Other Guy
Luke Combs
215
Things A Man Oughta Know
Lainey Wilson
216
Thought You Should Know
Morgan Wallen
217
Til Further Notice
Travis Scott Featuring James Blake & 21 Savage
218
Tit For Tat
Tate McRae
219
Too Late
The Weeknd
220
Topia Twins
Travis Scott Featuring Rob49 & 21 Savage
221
Touch The Sky
Future
222
Toxic Till The End
ROSE
223
Tradesman
Zach Bryan
224
Truck Bed
HARDY
225
Tu Name
Fuerza Regida
226
Tucson Too Late
Jordan Davis
227
Turks & Caicos
Rod Wave Featuring 21 Savage
228
Umm Hmm
YoungBoy Never Broke Again
229
Us Vs. Them
$uicideBoy$
230
Us.
Gracie Abrams Featuring Taylor Swift
231
WE (Warm Embrace)
Chris Brown
232
We Almost Broke Up Again Last Night
Sabrina Carpenter
233
What Do I Do
SZA
234
What If I Told You That I Love You
Ali Gatie
235
Wi$h Li$t
Taylor Swift
236
Wild Hearts
Keith Urban
237
Wildflowers And Wild Horses
Lainey Wilson
238
Wood
Taylor Swift
239
YaYa
6ix9ine
240
gp
Gunna

In [147]:
row = filtered_hot100_lyrics_df[(filtered_hot100_lyrics_df["title"]=="(There's No Place Like) Home For The Holidays (1959)") & (filtered_hot100_lyrics_df["performer"] == "Perry Como With Mitchell Ayers And His Orchestra")]
row

,title,performer,chart_weeks,wks_on_chart,peak_pos,plain_lyrics
5,(There's No Place Like) Home For The Holidays ...,Perry Como With Mitchell Ayers And His Orchestra,"[2023-01-07, 2025-12-20, 2025-12-27, 2026-01-03]",4,22,"Oh, there's no place like home for the holiday..."

In [148]:
lyrics = row["plain_lyrics"].iloc[0]
print(lyrics)

Oh, there's no place like home for the holidays
'Cause no matter how far away you roam
When you pine for the sunshine of a friendly gaze
For the holidays you can't beat home sweet home
I met a man who lives in Tennessee, he was headin' for
Pennsylvania and some homemade pumpkin pie
From Pennsylvania folks are travellin'
Down to Dixie's sunny shore
From Atlantic to Pacific
Gee the traffic is terrific
Oh, there's no place like home for the holidays
'Cause no matter how far away you roam
If you wanna to be happy in a million ways
For the holidays you can't beat home sweet home
Take a bus, take a train, go and hop an aeroplane
Put the wife an' kiddies in the family car
For the pleasure that you bring when you make that doorbell ring
No trip could be too far
I met a man who lives in Tennessee, he was headin' for
Pennsylvania and some homemade pumpkin pie (some pumpkin pie)
From Pennsylvania folks are travellin'
Down to Dixie's sunny shore
From Atlantic to Pacific
Gee the traffic is terrific
Oh, there's no place like home for the holidays
'Cause no matter how far away you roam
If you want to be happy in a million ways
For the holidays you can't beat home sweet home
For the holidays you can't beat home sweet home

In [149]:
"\n\n" in lyrics

False

In [150]:
sections, num_lines = chunk_song_lyrics(lyrics)

ValueError: Could not split lyrics into multiple sections.

In [151]:
from src.chunk_lyrics import LYRICS_SECTION_SEPARATOR_PATTERN
import re
sections = [
        section.strip()
        for section in re.split(LYRICS_SECTION_SEPARATOR_PATTERN, lyrics)
        if section.strip()
    ]
len(sections)

1

In [152]:
"a\nb".split("\n\n")

['a\nb']

In [153]:
"".split("\n\n")

['']

In [141]:
row = filtered_hot100_lyrics_df[(filtered_hot100_lyrics_df["title"]=="gp") & (filtered_hot100_lyrics_df["performer"] == "Gunna")]
row

,title,performer,chart_weeks,wks_on_chart,peak_pos,plain_lyrics
4070,gp,Gunna,[2025-08-23],1,87,I'm 'bout to start cryin' right now\nAnd I'm s...

In [142]:
lyrics = row["plain_lyrics"].iloc[0]
print(lyrics)

I'm 'bout to start cryin' right now
And I'm so emotional
Like, my pussy is so good
Like, it's so good
(Run that back, Turbo)
Fuck
That my lil' woe, she been pullin' up on us
Come right to the spot, I put dick in her stomach (dick in her stomach)
Play with that pussy, play with some more money (yeah)
Young nigga rich, and I keep a ho comin' (keep a ho comin')
Shades on my face, all I see is abundance
Cop the new Cullinan truck like it's nothin'
Ridin' in the spaceship with stars in the roof
And you still watchin' out for the Johnnies (Still watchin' out for the Johnnies)
Lil' mama bad (lil' mama bad), stampin' her passport (uh)
Money on the dashboard (money in the dash), two hundred on the dash (board)
Strapped like a task force (force), hit her from the back (hit her from the back)
Bitch, I'm a bad boy (boy), put her on the tab
Allergic to broke and I heard it's contagious
Been rappin' all night and I count it up daily (count it)
Breakin' her back, got her callin' me "Baby"
Pull up with ten, she know I 'preciate it (ten)
Pull up to the crib, the neighborhood gated
Residency for the summer is Vegas
Spirit of Ecstasy, cruise in Miss Daisy (cruise)
I'm floatin' in the back of the Mercedes (floatin' in the back of the Mercedes)
Floatin' on the track got me famous, uh
Fuckin' this ho to a cadence (fuckin' this ho to a cadence)
Marble in the spot, got it stainless (uh)
The rich understand my language (the rich understand my language)
You see the pretty picture I painted? (I painted)
You see her pretty face? I paint it (I paint it)
Stackin' more cakes than Danish
We lit 'cross the States, and they hate it
Lil' mama bad (lil' mama bad), stampin' her passport (uh)
Money on the dashboard (money in the dash), two hundred on the dash (board)
Strapped like a task force (force), hit her from the back (hit her from the back)
Bitch, I'm a bad boy (boy), put her on the tab

In [143]:
"\n\n" in lyrics

False

In [145]:
sections = [
        section.strip()
        for section in re.split(LYRICS_SECTION_SEPARATOR_PATTERN, lyrics)
        if section.strip()
    ]
len(sections)

1

Observation: Some plain_lyrics entries don't have predefined sections. A fallback option is needed to chunk them every 4 lines.

In [159]:
for i in range(0, 11, 2):
    print(i+2)

2
4
6
8
10
12

In [19]:
for i in range(0, 1, 2):
    print(i)

0

In [18]:
"123".splitlines()

['123']

---

In [21]:
from src.chunk_lyrics import build_chunk_documents
documents = build_chunk_documents(filtered_hot100_lyrics_df)

0
Beautiful Trip
Kid Cudi

ValueError: All lyrics were merged into one section. Please set min_lines smaller.

In [22]:
row = filtered_hot100_lyrics_df[(filtered_hot100_lyrics_df["title"]=="Beautiful Trip") & (filtered_hot100_lyrics_df["performer"] == "Kid Cudi")]
row

,title,performer,chart_weeks,wks_on_chart,peak_pos,plain_lyrics
354,Beautiful Trip,Kid Cudi,[2020-12-26],1,100,"Oh, oh\nOh\nThree (three, two, one)"

Problem detected: the song "Beautiful Trip" by "Kid Cudi" is just 37 seconds, and only has a few lyrics, not enough to chunk.

In [23]:
lyrics = row["plain_lyrics"].iloc[0]
lyrics

'Oh, oh\nOh\nThree (three, two, one)'

In [26]:
sections, num_lines = chunk_song_lyrics(lyrics)

In [27]:
sections

['Oh, oh\nOh\nThree (three, two, one)']

In [25]:
num_lines

[3]

In [33]:
from src.chunk_lyrics import force_chunk_song_lyrics
sections, num_lines = force_chunk_song_lyrics(lyrics)

ValueError: All lyrics are force-chunked into one section. Please set lines_per_chunk smaller.

In [35]:
sections, num_lines = force_chunk_song_lyrics(lyrics)

Lyrics are too short to chunk.

In [37]:
from src.chunk_lyrics import chunk_song_lyrics_with_fallback
sections, num_lines = chunk_song_lyrics_with_fallback(lyrics)

Lyrics are too short to chunk.

In [38]:
len(sections)

1

Problem solved!

---

In [36]:
documents = build_chunk_documents(filtered_hot100_lyrics_df)

Lyrics are too short to chunk.

ValueError: All lyrics were merged into one section. Please set min_lines smaller.